[package]
name = "sentinel-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
toml = "0.8"
figment = { version = "0.10", features = ["toml", "env"] }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true }
sentinel-domain = { path = "../domain" }

[dev-dependencies]
tempfile = "3"