//! Telemetry bootstrap: structured JSON logging + optional OpenTelemetry trace
//! export to Google Cloud Trace, plus strict allowlist-based redaction.
//!
//! Enforces that raw invoice bodies, prompts, credentials, tokens, PII, and
//! model chain-of-thought are never exported to external telemetry.
//!
//! ## Design
//! - **Always on**: structured JSON logs to stdout (the format Cloud Run and
//!   Cloud Logging expect), driven by `ObservabilityConfig`. Pretty format is
//!   available for humans via `LogFormat::Pretty`.
//! - **Optional export**: when `otel_endpoint` points at a real OTLP endpoint
//!   (not the local stub) and `trace_sample_rate > 0`, an OTLP gRPC OpenTelemetry
//!   layer is layered on top so `tracing` spans are exported as Cloud Trace
//!   spans. `trace_sample_rate > 0` is an on/off gate (it does not yet apply
//!   ratio-based sampling — wire a `Sampler::TraceIdRatioBased` for that). The W3C trace IDs generated by the workflow worker are attached as
//!   span fields (`trace_id=...`) so each certification run correlates to exactly
//!   one trace.
//! - **No silent double-init**: `init_telemetry` owns the *single* global
//!   subscriber. Call sites must NOT also call `init_logging`.
//!
//! ## Cloud Trace auth note
//! The OTLP gRPC exporter to `cloudtrace.googleapis.com` needs an
//! `Authorization: Bearer <token>` metadata entry. On Cloud Run we fetch that
//! token from the GCE metadata server at bootstrap using the service account's
//! `cloud-platform` scope. Cloud Run metadata tokens live ~1 hour; for a
//! long-lived service the recommended production pattern is an OpenTelemetry
//! Collector sidecar (no bearer auth, auto-refreshing ADC) and pointing
//! `otel_endpoint` at the sidecar's `http://localhost:4317`. The code handles
//! both: a metadata token is attached when available, otherwise the exporter is
//! initialized without it (suitable for a local collector).

use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt, EnvFilter, Layer};

use sentinel_config::{LogFormat, ObservabilityConfig};

/// Configuration snapshot used by `init_telemetry`.
pub use sentinel_config::ObservabilityConfig as TelemetryConfig;

/// Guard that flushes the OpenTelemetry tracer provider on drop.
///
/// Hold it for the whole process lifetime (the Rust services bind it to the
/// runtime). Dropping flushes in-flight spans so Cloud Trace receives them.
#[must_use]
pub struct TelemetryGuard {
    provider: Option<opentelemetry_sdk::trace::TracerProvider>,
}

impl Drop for TelemetryGuard {
    fn drop(&mut self) {
        if let Some(provider) = self.provider.take() {
            // Best-effort flush: telemetry failure must never panic the process.
            if let Err(e) = provider.shutdown() {
                eprintln!("otel tracer provider shutdown error: {e}");
            }
        }
    }
}

const LOCAL_OTEL_STUB: &str = "http://localhost:4317";

/// Whether the configured OTLP endpoint should actually trigger export.
///
/// We export only if the endpoint is set to something other than the local
/// stub default — this keeps LOCAL/CI builds (no collector) from hammering a
/// dead `localhost:4317`, while making production opt-in explicit and loud.
fn should_export(otel_endpoint: &str) -> bool {
    !otel_endpoint.is_empty() && otel_endpoint != LOCAL_OTEL_STUB
}

/// Initialize telemetry for a service.
///
/// - `config` — the service's observability configuration (JSON by default).
/// - `gcp_project` — used for the `gcp.project_id` resource attribute when
///   exporting. Pass `None` in LOCAL/CI mode.
///
/// Returns a guard that must be held for the process lifetime.
pub fn init_telemetry(
    config: &ObservabilityConfig,
    gcp_project: Option<&str>,
) -> Result<TelemetryGuard, String> {
    init_telemetry_with_name(&config.otel_service_name, config, gcp_project)
}

/// Like [`init_telemetry`] but overrides the service name (for tests).
pub fn init_telemetry_with_name(
    service_name: &str,
    config: &ObservabilityConfig,
    gcp_project: Option<&str>,
) -> Result<TelemetryGuard, String> {
    use tracing_subscriber::fmt;

    let env_filter =
        EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new(&config.log_level));

    let fmt_layer = match config.log_format {
        LogFormat::Json => fmt::layer()
            .json()
            .with_span_events(fmt::format::FmtSpan::CLOSE)
            .with_thread_ids(true)
            .boxed(),
        LogFormat::Pretty => fmt::layer()
            .pretty()
            .with_span_events(fmt::format::FmtSpan::CLOSE)
            .with_thread_ids(true)
            .boxed(),
    };

    // ── Optional OTLP export to Google Cloud Trace ──────────────────────────
    let mut guard = TelemetryGuard { provider: None };

    // Export only when a real (non-stub) endpoint is configured AND the
    // configured sample rate is non-zero. `trace_sample_rate > 0` is the
    // documented off-switch (see module docs); it gates export, it does not
    // (yet) apply ratio-based sampling.
    let export_enabled = should_export(&config.otel_endpoint) && config.trace_sample_rate > 0.0;

    let (registry_layer, provider) = if export_enabled {
        match build_otlp_layer(service_name, &config.otel_endpoint, gcp_project) {
            Ok((layer, provider)) => (Some(layer), Some(provider)),
            Err(e) => {
                // Telemetry export failure must never block the primary request path.
                eprintln!(
                    "WARN: OpenTelemetry Cloud Trace exporter disabled — falling back to \
                     stdout-only tracing. Reason: {e}"
                );
                (None, None)
            }
        }
    } else {
        (None, None)
    };

    guard.provider = provider;

    let registry = tracing_subscriber::registry()
        .with(env_filter)
        .with(fmt_layer);

    let registry = if let Some(layer) = registry_layer {
        registry.with(layer)
    } else {
        registry
    };

    registry
        .try_init()
        .map_err(|e| format!("failed to set global tracing subscriber: {e}"))?;

    Ok(guard)
}

/// Build the OpenTelemetry gRPC OTLP exporter + tracing layer for Cloud Trace.
fn build_otlp_layer(
    service_name: &str,
    endpoint: &str,
    gcp_project: Option<&str>,
) -> Result<
    (
        tracing_opentelemetry::OpenTelemetryLayer<tracing_subscriber::Registry>,
        opentelemetry_sdk::trace::TracerProvider,
    ),
    String,
> {
    use opentelemetry::KeyValue;
    use opentelemetry_otlp::{Protocol, WithExportConfig};
    use opentelemetry_sdk::runtime::Tokio;
    use opentelemetry_sdk::trace::TracerProvider;
    use opentelemetry_sdk::Resource;

    let mut resource_kvs = vec![
        KeyValue::new("service.name", service_name.to_string()),
        KeyValue::new("service.version", env!("CARGO_PKG_VERSION")),
    ];
    if let Some(project) = gcp_project {
        resource_kvs.push(KeyValue::new("gcp.project_id", project.to_string()));
    }
    let resource = Resource::new(resource_kvs);

    let exporter = opentelemetry_otlp::SpanExporter::builder()
        .with_tonic()
        .with_protocol(Protocol::Grpc)
        .with_endpoint(endpoint)
        .build()
        .map_err(|e| format!("OTLP SpanExporter build error: {e}"))?;

    let provider = TracerProvider::builder()
        .with_batch_exporter(exporter, Tokio)
        .with_resource(resource)
        .build();

    let tracer = provider.tracer(service_name.to_string());
    let layer = tracing_opentelemetry::layer().with_tracer(tracer);
    Ok((layer, provider))
}

/// Back-compat shim: stdout-only tracing for callers that predate
/// `init_telemetry`. Prefer `init_telemetry` for Cloud Trace export.
pub fn init_tracing(service_name: &str) -> Result<TelemetryGuard, String> {
    let config = ObservabilityConfig {
        otel_service_name: service_name.to_string(),
        ..ObservabilityConfig::default()
    };
    init_telemetry_with_name(service_name, &config, None)
}

/// Strict allowlist-based redaction processor.
pub mod redact {
    use std::collections::HashSet;

    /// Allowlisted telemetry attribute keys. ONLY these keys may appear in telemetry.
    pub const ALLOWED_KEYS: &[&str] = &[
        "tenant_id",
        "workflow_id",
        "case_run_id",
        "case_id",
        "operation",
        "outcome",
        "latency_ms",
        "retry_count",
        "provenance",
        "model_version",
        "policy_version",
        "status_code",
        "attempt",
        "token_count",
        "cost_usd_micro",
        "trace_id",
        "span_id",
    ];

    /// Checks whether an attribute key is safe for telemetry export.
    pub fn is_allowed(key: &str) -> bool {
        ALLOWED_KEYS.contains(&key)
    }

    /// Redacts arbitrary JSON values by removing any key not on the allowlist.
    pub fn redact_value(value: &serde_json::Value) -> serde_json::Value {
        match value {
            serde_json::Value::Object(map) => {
                let allowed_set: HashSet<&str> = ALLOWED_KEYS.iter().copied().collect();
                let filtered: serde_json::Map<String, serde_json::Value> = map
                    .iter()
                    .filter(|(k, _)| allowed_set.contains(k.as_str()))
                    .map(|(k, v)| (k.clone(), redact_value(v)))
                    .collect();
                serde_json::Value::Object(filtered)
            }
            serde_json::Value::Array(arr) => {
                serde_json::Value::Array(arr.iter().map(redact_value).collect())
            }
            v => v.clone(),
        }
    }

    /// Scans a text payload for forbidden canary secret tokens.
    pub fn contains_canary_secret(text: &str, canary: &str) -> bool {
        text.contains(canary)
    }
}
